apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-flux
  region: us-east-1

vpc:
  sharedNodeSecurityGroup: sg-0810a23af1d93fbf2
  id: vpc-0601f98fc9be4e688
  subnets:
    private:
      private-one:
        id: subnet-098ea6021fa7f2659
      private-two:
        id: subnet-0f78f92e46fdbe192
    public:
      public-one: 
        id: subnet-0f56996f87e9b4bd4
      public-two:
        id: subnet-0308fde92ec4a62df

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: c5d.xlarge
    desiredCapacity: 1
    privateNetworking: true
